### ISSUE TITLE
ValueError: 3 is not in list

### ISSUE THREAD

**Issue by dareksan3KY** [DimaLeon2000/PyDeskMates#1]
Traceback (most recent call last):
  File "C:\Users\KY\Desktop\1\main.py", line 757, in <module>
    app = App()
          ^^^^^
  File "C:\Users\KY\Desktop\1\main.py", line 598, in __init__
    self.sprite_handler.add_sprite(WIDTH // 2, HEIGHT // 2)
  File "C:\Users\KY\Desktop\1\main.py", line 473, in add_sprite
    self.sprites.append(SpriteUnit(handler=self, x=x, y=y))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KY\Desktop\1\main.py", line 146, in __init__
    self.image_ind = list(self.handler.app.frames.keys()).index(3)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 3 is not in list

Simply this not even launching.
![err](https://github.com/DimaLeon2000/PyDeskMates/assets/42091569/d985d0fe-c300-497b-97ed-a7cc755eae51)

**Comment by DimaLeon2000** [comment]
1. Do you have folders with files of specific characters in the root directory? The files for characters (like Oska, Tahni, etc.) are crucial. Be sure to download them [here](https://archive.org/details/Deskmates) or [here](https://archive.org/details/more-deskmates), since the original DeskMates are now abandonware.
2. Have you changed the variables `character`, `working_dir` and `data_directory` to proper parameters?

**Comment by dareksan3KY** [comment]
I did this: and I think I'm doing it wrong because I still have the same error
![d1](https://github.com/DimaLeon2000/PyDeskMates/assets/42091569/4be12092-6d1b-4d28-a22b-2bc055a24109)
![d2](https://github.com/DimaLeon2000/PyDeskMates/assets/42091569/55b7c9ba-e2b8-4f20-82b5-7c513accd8c1)

**Comment by DimaLeon2000** [comment]
Don't change the variables in the App class' `__init__` function -- change them in the `if __name__ == '__main__'` condition instead. Plus, the `character` variable should **not** be the full directory path -- it should the directory name.

**Comment by dareksan3KY** [comment]
ok, it started working when I did this with "data_directory"...
![d1](https://github.com/DimaLeon2000/PyDeskMates/assets/42091569/53b07ae4-4317-4913-8801-872c4fb9d7d1)

so I guess we can close the issue

+ This whole problem can be considered a tutorial because there is no tutorial by default
